# DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:mysql://10.171.55.193/uba_db?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: test
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql