spring:
  datasource:
    username: root
    password: 'Zhx980906+1s'
    # serverTimezone=UTC 解决时区问题
    url: jdbc:mysql://124.221.77.111:3306/shanyutu?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    # mysql8 以上使用 cj
    driver-class-name: com.mysql.cj.jdbc.Driver
